# Generated by Django 4.1.1 on 2024-09-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('rowId', models.AutoField(primary_key=True, serialize=False)),
                ('crypto_name', models.CharField(max_length=10)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
